### ISSUE TITLE
Add more GUI blocks to avoid user panick

### ISSUE THREAD

**Issue by gioagu** [tudelft3d/3DCityDB-Tools-for-QGIS#52]
In the Layer Loader, during layer creation or refreshing, more dialog widgets should be disabled while the thread is on-going.

E.g.: PostgreSQL connection groupbox, CityDB groupbox, Basemap groupbox, Close connection button.

Of course, to be re-enabled as soon as the thread finishes.

**Comment by tendaiwbm** [comment]
While creating or refreshing layers, clicking "Close current connection" can cause Python to raise a "connection already closed" error.

OR QGIS might crash suddenly.

In the db, the create or refresh layers transaction will still complete.

BUT there will be no communication back to the UI because there will be no open connection.

**Comment by gioagu** [comment]
Solved in version 0.8.7

Added several blocks to avoid clicking around when a thread is running. Applies to: Layer Loader, Bulk Deleter, QGIS Pkg Administrator.

This should prevent what described above. If not, please reopen.
